// Lista completa de setores conforme Norma Zero ISGH (Tabela IV)

export type Setor = { sigla: string; nome: string };

export const SETORES: Setor[] = [
  { sigla: "AGT", nome: "Agência Transfusional" },
  { sigla: "ALM", nome: "Almoxarifado" },
  { sigla: "AMB", nome: "Ambulatório Geral" },
  { sigla: "AMO", nome: "Ambulatório Obstétrico" },
  { sigla: "APO", nome: "Apoio" },
  { sigla: "ASS", nome: "Assistencial" },
  { sigla: "BLH", nome: "Banco de Leite Humano" },
  { sigla: "BIO", nome: "Bioquímica" },
  { sigla: "CME", nome: "Central de Material e Esterilização" },
  { sigla: "CCG", nome: "Centro Cirúrgico Geral" },
  { sigla: "CET", nome: "Centro de Estudos" },
  { sigla: "CPN", nome: "Centro de Parto Normal" },
  { sigla: "CTI", nome: "Central de Transportes Internos" },
  { sigla: "CLC", nome: "Clínica Cirúrgica" },
  { sigla: "COV", nome: "Clínica COVID" },
  { sigla: "CLO", nome: "Clínica Obstétrica" },
  { sigla: "PCV", nome: "Clínica Pediátrica COVID" },
  { sigla: "CTO", nome: "Clínica Traumato Ortopédica" },
  { sigla: "CCI", nome: "Coordenadoria de Conformidade e Controle Interno" },
  { sigla: "EEP", nome: "Coordenadoria de Educação Permanente, Ensino e Pesquisa" },
  { sigla: "COF", nome: "Custos, Orçamento e Faturamento" },
  { sigla: "UCV", nome: "UTI COVID" },
  { sigla: "UPC", nome: "UTI Pediátrica COVID" },
  { sigla: "CLM", nome: "Clínica Médica" },
  { sigla: "CLP", nome: "Clínica Pediátrica" },
  { sigla: "CPL", nome: "Cuidados Paliativos" },
  { sigla: "DIR", nome: "Direção" },
  { sigla: "DPS", nome: "Departamento Pessoal" },
  { sigla: "EMG", nome: "Emergência" },
  { sigla: "EMO", nome: "Emergência Obstétrica" },
  { sigla: "EMP", nome: "Emergência Pediátrica" },
  { sigla: "END", nome: "Endoscopia Digestiva Alta" },
  { sigla: "ENF", nome: "Enfermagem" },
  { sigla: "CAN", nome: "Enfermaria Canguru" },
  { sigla: "ENG", nome: "Engenharia Clínica" },
  { sigla: "ESG", nome: "Escola de Saúde e Gestão" },
  { sigla: "EST", nome: "Estratégia" },
  { sigla: "FIS", nome: "Fisioterapia" },
  { sigla: "FON", nome: "Fonoaudiologia" },
  { sigla: "GER", nome: "Geral" },
  { sigla: "HIG", nome: "Higienização" },
  { sigla: "HMT", nome: "Hematologia" },
  { sigla: "HEM", nome: "Hemodinâmica" },
  { sigla: "IMU", nome: "Imunológico" },
  { sigla: "HOT", nome: "Hotelaria" },
  { sigla: "LAB", nome: "Laboratório de Análises Clínicas" },
  { sigla: "MAN", nome: "Manutenção" },
  { sigla: "MED", nome: "Medicina" },
  { sigla: "NAF", nome: "Núcleo Administrativo Financeiro" },
  { sigla: "NAC", nome: "Núcleo de Atendimento ao Cliente" },
  { sigla: "FAR", nome: "Núcleo de Assistência Farmacêutica" },
  { sigla: "NPL", nome: "Núcleo de Planejamento e Logística" },
  { sigla: "NHP", nome: "Núcleo de Hotelaria e Patrimônio" },
  { sigla: "NHE", nome: "Núcleo Hospitalar de Epidemiologia" },
  { sigla: "NGP", nome: "Núcleo de Gestão de Pessoas" },
  { sigla: "NGS", nome: "Núcleo de Gestão e Segurança do Paciente" },
  { sigla: "NCS", nome: "Núcleo de Contratação e Serviços" },
  { sigla: "SUP", nome: "Núcleo de Suprimentos" },
  { sigla: "NTI", nome: "Núcleo de Tecnologia da Informação" },
  { sigla: "NEA", nome: "Núcleo de Engenharia e Arquitetura" },
  { sigla: "NFC", nome: "Núcleo Financeiro-Contábil" },
  { sigla: "NUT", nome: "Nutrição" },
  { sigla: "OBT", nome: "Obstetrícia" },
  { sigla: "ODO", nome: "Odontologia" },
  { sigla: "OUV", nome: "Ouvidoria" },
  { sigla: "PAC", nome: "Pactuação" },
  { sigla: "PAT", nome: "Patrimônio" },
  { sigla: "PSI", nome: "Psicologia" },
  { sigla: "RHU", nome: "Recursos Humanos" },
  { sigla: "REG", nome: "Regulação" },
  { sigla: "ROU", nome: "Rouparia" },
  { sigla: "SAD", nome: "Serviço de Atendimento Domiciliar" },
  { sigla: "SIH", nome: "Serviço de Controle de Infecção Hospitalar" },
  { sigla: "IMG", nome: "Serviço de Imagem e Apoio Diagnóstico" },
  { sigla: "SES", nome: "Serviço Social" },
  { sigla: "SMT", nome: "Serviços Especializados em Engenharia de Segurança e em Medicina do Trabalho" },
  { sigla: "SGQ", nome: "Sistema de Gestão da Qualidade" },
  { sigla: "TOC", nome: "Terapia Ocupacional" },
  { sigla: "TRA", nome: "Traumato" },
  { sigla: "AVC", nome: "Unidade de AVC" },
  { sigla: "UCE", nome: "Unidade de Cuidados Especiais" },
  { sigla: "UCI", nome: "Unidade de Cuidados Intermediários" },
  { sigla: "UTI", nome: "Unidade de Terapia Intensiva Adulto" },
  { sigla: "TIC", nome: "Unidade de Terapia Intensiva COVID" },
  { sigla: "NEO", nome: "Unidade de Terapia Intensiva Neonatal" },
  { sigla: "UTP", nome: "Unidade de Terapia Intensiva Pediátrica" },
];

export const SETORES_OPTIONS = SETORES.map(s => ({
  value: s.sigla,
  label: `${s.nome} (${s.sigla})`,
}));

// Tipos de documento conforme formulário
export const TIPOS_REQUISICAO = ["Elaboração", "Revisão"] as const;
export const ABRANGENCIAS = ["Sede", "Institucional"] as const;

export const TIPOS_DOCUMENTO_SOLICITACAO = [
  "Política", "Regimento", "Regulamento", "Diretrizes",
  "Ficha Técnica do Indicador", "Fichas e Formulários", "Fluxogramas",
  "Instruções de Trabalho", "Manual", "Mapeamento de Processos",
  "Normas Técnicas", "Normatização", "Planos", "Plano de Contingência",
  "Plano de Segurança do Paciente", "Protocolo", "Protocolo Clínico Gerenciado",
  "Protocolos de Segurança Gerenciados", "Procedimento Operacional Padrão",
  "Interação de Processos", "Modelagem de Processos", "Pactuações",
] as const;
